import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";
import "../styles/css/main.css"

// TODO: Kommenter ut om du ønsker å bruke .css

import '../styles/css/main.css'
// TODO: Kommenter ut om du ikke ønsker å bruke tailwind
//import "../styles/tailwind/main.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
        className="layout"
        data-testid="layout"
      >
        <nav className="layout_nav">
          <h1 className="logo" data-testid="logo">
            <Link href="/">Mikro LMS</Link>
          </h1> 
          <ul className="nav_links" data-testid="nav">
            <li className="nav_item" data-testid="nav_courses">
            <Link href="/courses">Kurs</Link>
            </li>
            <li className="text-base font-semibold" data-testid="nav_new">
            <Link href="/course">Nytt kurs</Link>
            </li>
          </ul>
        </nav>
        <main className="layout_main">
          {children}  { /*SRC: kilde: https://chatgpt.com*/}
        </main>
        <footer className="layout_footer" data-testid="footer">
          <p>Mikro LMS AS, 2024</p>
          <p>99 00 00 00, mail@lms.no</p>
        </footer>
      </div>
  );
}

import React from "react";
