import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";
import "../styles/css/main.css"

// TODO: Kommenter ut om du ønsker å bruke .css

import '../styles/css/main.css'
// TODO: Kommenter ut om du ikke ønsker å bruke tailwind
//import "../styles/tailwind/main.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
        className="mx-auto grid min-h-screen w-full max-w-7xl grid-rows-[auto_minmax(900px,_1fr)_30px]"
        data-testid="layout"
      >
        <nav className="mt-6 mb-12 flex justify-between">
          <h1 className="text-lg font-bold uppercase" data-testid="logo">
            <Link href="/">Mikro LMS</Link>{/*  Hovedside main */}
          </h1> 
          <ul className="flex gap-8" data-testid="nav">
            <li className="text-base font-semibold" data-testid="nav_courses">
            <Link href="/courses">Kurs</Link>{/*  Side kurs */}
            </li>
            <li className="text-base font-semibold" data-testid="nav_new">
            <Link href="/course">Nytt kurs</Link>{/*  nytt kurs */}
            </li>
          </ul>
        </nav>
        <main className="h-full">
          <p>Siden er tom</p>
        </main>
        <footer className="flex justify-between" data-testid="footer">
          <p>Mikro LMS AS, 2024</p>
          <p>99 00 00 00, mail@lms.no</p>
        </footer>
      </div>
  );
}

import React from "react";
